--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/David-pm-pl/PowerfulAdsFilter
build-by-default: true
branches:
- stable
projects:
  PowerfulAdsFilter:
    path: ""
    icon: "assets/images/icon.png"
    lint:  
       phpstan: false
...
