--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/David-pm-pl/AdsFilter
build-by-default: true
branches:
- stable
projects:
  AdsFilter:
    path: ""
    icon: "assets/images/icon.png"
    lint:  
       phpstan: false
...
